name: Deploy to Fly.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify backend sources
        run: python -m compileall app

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          set -euo pipefail
          if [ -z "${FLY_API_TOKEN:-}" ]; then
            echo "Missing FLY_API_TOKEN secret" >&2
            exit 1
          fi
          if [ -z "${FLY_APP_NAME:-}" ]; then
            echo "Missing FLY_APP_NAME secret" >&2
            exit 1
          fi

          export FLY_ACCESS_TOKEN="${FLY_API_TOKEN}"

          BUILD_ARGS=""
          if [ -n "${VITE_API_BASE_URL:-}" ]; then
            BUILD_ARGS="--build-arg VITE_API_BASE_URL=${VITE_API_BASE_URL}"
          fi

          flyctl deploy --remote-only --app "${FLY_APP_NAME}" ${BUILD_ARGS}
